version: '3.8'

services:
  database:
    image: postgres:15.1-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - local
  app:
    build: 
      context: .
    ports: 
      - 50052:50052
      - 9184:9184
    environment:
      - WAIT_HOSTS=database:5432
      - DATABASE_URL=postgres://rust:password@database:5432/rustdb
    depends_on:
      - database
    networks:
      - local
  # cadvisor:
  #   image: gcr.io/cadvisor/cadvisor:v0.47.1
  #   container_name: cadvisor-go
  #   privileged: true
  #   platform: "linux/amd64"
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - /:/rootfs:ro
  #     - /var/run:/var/run:rw
  #     - /sys:/sys:ro
  #     - /var/lib/docker/:/var/lib/docker:ro
  #   networks:
  #     - rust-app
volumes:
  database:
    driver: local
networks:
  local:
    name: local